insert into Teams (Slogan, Name, LogoUrl, ReceieveNotifications, isActive, AddedBy,AddedByDatetime,LastUpdatedBy,LastUpdatedByDatetime) 
values ('transition cross-platform web services', 'Golf Alfa', 'http://dummyimage.com/232x137.png/dddddd/000000', 1, 0,2,GETDATE(),2,GETDATE()),
('empower interactive systems', 'Uniform Zulu', 'http://dummyimage.com/129x158.png/5fa2dd/ffffff', 0, 1,2,GETDATE(),2,GETDATE()),
('redefine ubiquitous systems', 'Delta Oscar', 'http://dummyimage.com/106x130.png/cc0000/ffffff', 0, 1,2,GETDATE(),2,GETDATE()),
('scale vertical content', 'Charlie Juliett', 'http://dummyimage.com/143x159.png/ff4444/ffffff', 0, 1,2,GETDATE(),2,GETDATE()),
('streamline scalable architectures', 'X-ray Charlie', 'http://dummyimage.com/246x154.png/ffffff/5fa2dd1 ',0, 1,2,GETDATE(),2,GETDATE()),
('strategize magnetic action-items', 'Uniform Charlie', 'http://dummyimage.com/246x219.png/cc0000/ffffff', 1, 1,2,GETDATE(),2,GETDATE()),
('recontextualize killer infrastructures', 'Tango Victor', 'http://dummyimage.com/189x180.png/5fa2dd/ffffff', 0, 1,2,GETDATE(),2,GETDATE()),
('evolve granular interfaces', 'Romeo Alfa', 'http://dummyimage.com/153x131.png/5fa2dd/ffffff', 0, 1,2,GETDATE(),2,GETDATE()),
('implement open-source e-services', 'Tango Echo', 'http://dummyimage.com/231x206.png/5fa2dd/ffffff', 1, 1,2,GETDATE(),2,GETDATE()),
('unleash value-added architectures', 'Yankee Kilo', 'http://dummyimage.com/238x225.png/ff4444/ffffff', 0, 1,2,GETDATE(),2,GETDATE()),
('transition e-business infrastructures', 'Tango Juliett', 'http://dummyimage.com/250x183.png/cc0000/ffffff', 0, 1,2,GETDATE(),2,GETDATE()),
('brand customized interfaces', 'Echo Kilo', 'http://dummyimage.com/226x238.png/5fa2dd/ffffff', 0, 1,2,GETDATE(),2,GETDATE()),
('unleash global e-tailers', 'Romeo Oscar', 'http://dummyimage.com/207x215.png/dddddd/000000', 1, 1,2,GETDATE(),2,GETDATE()),
('drive vertical models', 'Yankee Golf', 'http://dummyimage.com/183x195.png/5fa2dd/ffffff', 1, 1,2,GETDATE(),2,GETDATE()),
('drive next-generation infrastructures', 'Zulu Juliett', 'http://dummyimage.com/236x137.png/cc0000/ffffff', 1, 1,2,GETDATE(),2,GETDATE()),
('scale rich systems', 'Delta Charlie', 'http://dummyimage.com/205x124.png/5fa2dd/ffffff', 1, 1,2,GETDATE(),2,GETDATE());